### ISSUE TITLE
精简ip库的问题

### ISSUE THREAD

**Issue by redstoneleo** [v2fly/geoip#28]
这里的说法是否有道理
https://github.com/Hackl0us/GeoIP2-CN
如果有，那么是否可以精简ip库减小搜寻量以提升查询速度？

**Comment by Loyalsoldier** [comment]
精简 IP 库可以缩短载入时间，但不能提升查询速度。

**Comment by redstoneleo** [comment]
谢谢！我也不是很懂，就想着应用更准确的IP库应该可以去除一些多余的无效IP段，这样子应该就可以减小查询总量吧
这里也有几个国内ip段的整理 https://github.com/iBug/pac/tree/release-20210710

**Comment by ayanamist** [comment]
由于 Loyalsoldier/geoip#31 问题的产生，这个需求是不是有必要再考虑一下，对路由器用户来说，现在40多M的dat文件有点太大了，但实际只取其中的CN数据而已

**Comment by Loyalsoldier** [comment]
本项目现已支持定制 geoip.dat 文件
