### ISSUE TITLE
2022/03/25 22:32:14 unknown config type

### ISSUE THREAD

**Issue by soranerai** [v2fly/geoip#38]
i made this config, but program show me an exception: unknown config type

thats my config.json:
```
{
  "input": [
    {
      "type": "text",
      "action": "add",
      "args": {
          "name": "ipv4",
          "uri": "blacklisted_ipv4",
          "onlyIPType": "ipv4"
      }
    },
    {
      "type": "text",
      "action": "add",
          "args": {
          "name": "ipv6",
          "uri": "blacklisted_ipv6",
          "onlyIPType": "ipv6"
      }
    }
  ],
  "output": [
    {
      "type": "v2rayGeoIPDat",
      "action": "output",
      "args": {
        "outputName": "russia_ips.dat",
        "wantedList": ["ipv4", "ipv6"]
      }
    }
  ]
}
```
I can't understand something? Advise me, please:)

**Comment by Loyalsoldier** [comment]
Cannot reproduce. Remember to use Go v1.18

**Comment by soranerai** [comment]
already have Go 1.18, 
OS image is **Ubuntu 20.04.4 LTS (GNU/Linux 5.10.60.1-microsoft-standard-WSL2 x86_64)**
also i tried to execute script on my server with Ubuntu 16.04, but it didn't work anyway.

there is files with ips:
[blacklisted_ipv6.txt](https://github.com/v2fly/geoip/files/8355021/blacklisted_ipv6.txt)
[blacklisted_ipv4.txt](https://github.com/v2fly/geoip/files/8355020/blacklisted_ipv4.txt)

can u check, script is working with my config and attached files?

**Comment by Loyalsoldier** [comment]
Works fine on my computer.

**Comment by soranerai** [comment]
Very strange.
Just tested on my own PC with Windows and it still doesn't work. This means that the problem is clearly not in the environment.
are you sure you are using my config?

**Comment by soranerai** [comment]
update: when I run the script through the debugger everything works. idk what the problem, but decided to let u know. have a nice day!
