### ISSUE TITLE
Change license to CC-BY-SA-4.0

### ISSUE THREAD

**Issue by kidonng** [v2fly/geoip#4]
This is the license used by the source database: https://dev.maxmind.com/geoip/geoip2/geolite2/#License

It's more appropriate than the current MIT license.

**Comment by SMillerDev** [comment]
The current license actually violates the original license
> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by Loyalsoldier** [comment]
Sorry for the delay. I'll change the license to CC-BY-SA-4.0.

**Comment by Loyalsoldier** [comment]
Done in https://github.com/v2fly/geoip/commit/bce47b96a07c15dd79db9771949594d553bb60f7
