### ISSUE TITLE
提升国内IP段的建议

### ISSUE THREAD

**Issue by redstoneleo** [v2fly/geoip#47]
本项目的国内IP段不太准，以至于会有类似问题https://github.com/Loyalsoldier/v2ray-rules-dat/issues/238
建议用https://github.com/Hackl0us/GeoIP2-CN 校准国内IP段

**Comment by kslr** [comment]
IP 库的选择主要是授权协议问题，这两份数据源都没有具体授权协议，IPIP 也没有回应过，因此不能使用。

**Comment by redstoneleo** [comment]
这种事情应该就不可能正大光明地授权了吧，只能心领神会吧~

gtranslate.cdn.haah.net和note.youdao.com的ip都被判为国外的了，很无语……

**Comment by redstoneleo** [comment]
经过我的测试，目前发现最准的还是这个 https://github.com/lionsoul2014/ip2region
