### ISSUE TITLE
Ipv6有3个段被错误的归类到cn.txt

### ISSUE THREAD

**Issue by Loukky** [v2fly/geoip#84]
2406:da00:e000::/40
2406:da1e::/32
2406:da2e::/36
这三个段目前由 Amazon宣告在AS16509上。
https://bgp.he.net/net/2406:da00:e000::/40
实际属地应该是在hk

**Comment by Loyalsoldier** [comment]
本项目 IP 数据来源于 MaxMind，不会进行手动人为修改。如果需要更精确的结果，建议自行构建。
